[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
calculatordapp = "yb7Vkoa9wgBpUCEyFEGnfoi2nyUUFsNG784xGaSKTVm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/workspaces/sbc-workspace/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
